### PR TITLE
fix crash when geometry is undefined

### PR DESCRIPTION
**Pull request by benkaiser**
Sometimes the geometry in some datasets (some extra features without geometrys)

Rather than crashing on this, just omit the record.

### CODE REVIEW

**Comment by orangejulius** [comment]
Nice catch! Bonus points if you write a test for this as well.

**Comment by benkaiser** [comment]
I know. Was easier to just switch to node archiver like was already
mentioned in this thread. It works a treat.

**Comment by orangejulius** [comment]
Fixed in #8

**Comment by benkaiser** [comment]
Oh my, serious apologies for my bizzare message above. Was in reply to a different github issue.

Thanks for adding the test @orangejulius

**Comment by orangejulius** [comment]
No worries, email is hard :P

**Pull request closed without merging**
